url(r'^participant/(?P<participantID>[0-9]+)$',views.participantIndex,name='participantIndex')
url(r'^participant/(?P<participantID>[0-9]+)/dashboard/$',views.participantDashboard,name='participantDashboard')
url(r'^participant/(?P<participantID>[0-9]+)/showCategoryList/$',views.showCategoryList,name='showCategoryList')
url(r'^participant/(?P<participantID>[0-9]+)/showCourseList/$',views.showCourseList,name='showCourseList')
url(r'^participant/(?P<participantID>[0-9]+)/showCourse/$',views.showCourse,name='showCourse')
url(r'^participant/(?P<participantID>[0-9]+)/enroll/(?P<participantID>[0-9]+)/$',views.enroll,name='enroll')
  
url(r'^instructor/(?P<instructorID>[0-9]+)$',views.instructorIndex,name='instructorIndex')
url(r'^instructor/(?P<instructorID>[0-9]+)/dashboard/$',views.instructorDashboard,name='instructorDashboard')
url(r'^instructor/(?P<instructorID>[0-9]+)/newCourse',views.newCourse,name='newCourse')
url(r'^instructor/(?P<instructorID>[0-9]+)/coursePage$',views.coursePage,name='coursePage')
url(r'^instructor/(?P<instructorID>[0-9]+)/(?P<courseID>[0-9]+)/newModule',views.newModule,name='newModule')
url(r'^instructor/(?P<instructorID>[0-9]+)/(?P<moduleID>[0-9]+)/$',views.modulePage,name="modulePage")
url(r'^instructor/(?P<instructorID>[0-9]+)/(?P<moduleID>[0-9]+)/$',views.newComponent,name="newComponent")
