# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Course'),
        ),
        migrations.AlterField(
            model_name='currentenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Course'),
        ),
    ]
