# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TakenCourse',
            new_name='CompletionRecord',
        ),
    ]
