# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdpuser',
            old_name='user',
            new_name='_user',
        ),
    ]
