# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20161028_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completionrecord',
            name='_user',
        ),
    ]
