# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_videocomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecomponent',
            name='content',
            field=models.ImageField(upload_to=''),
        ),
    ]
