# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_administrator_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='content',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
